import type { Item } from './types';
export function today(){return dateString(new Date());}
export function dateString(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function parseDate(value:string){const [y,m,d]=value.slice(0,10).split('-').map(Number);return new Date(y,m-1,d,12);}
export function validDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&dateString(parseDate(value))===value;}
export function heldDays(value:string,at=today()){const utc=(s:string)=>Date.parse(s.slice(0,10)+'T00:00:00Z');return Math.max(1,Math.round((utc(at)-utc(value))/86400000));}
export function unitCost(item:Item,extra=0):number|null{return item.costType==='per_use'?(item.usageCount>0?item.price/item.usageCount:null):item.price/(heldDays(item.purchaseDate)+extra);}
export function summarize(items:Item[]){const active=items.filter(x=>x.status==='using'),daily=active.filter(x=>x.costType==='daily');return {active,daily,value:active.reduce((s,x)=>s+x.price,0),burn:daily.reduce((s,x)=>s+(unitCost(x)||0),0),future:daily.reduce((s,x)=>s+(unitCost(x,30)||0),0)};}
export function validateItem(item:Omit<Item,'id'>){if(!item.name.trim())return '请填写物品名称';if(!Number.isFinite(item.price)||item.price<0||item.price>99999999)return '价格需为 0 到 99,999,999 之间的金额';if(!validDate(item.purchaseDate)||item.purchaseDate>today())return '请选择有效的购入日期，不能晚于今天';if(!Number.isSafeInteger(item.usageCount)||item.usageCount<0)return '使用次数需为非负整数';return '';}
export function readItems(raw:string):Item[]{const value:unknown=JSON.parse(raw);if(!Array.isArray(value))throw Error('数据格式无效');const ids=new Set<string>();return value.map((v:unknown)=>{if(!v||typeof v!=='object')throw Error('物品格式无效');const x=v as Item;if(typeof x.id!=='string'||!x.id||ids.has(x.id)||typeof x.name!=='string'||!Number.isFinite(x.price)||x.price<0||typeof x.purchaseDate!=='string'||!validDate(x.purchaseDate.slice(0,10))||!Number.isInteger(x.usageCount)||x.usageCount<0||!['daily','per_use'].includes(x.costType)||!['using','sold'].includes(x.status)||typeof x.category!=='string'||(x.icon!==undefined&&typeof x.icon!=='string'))throw Error('存在无法读取的物品记录');ids.add(x.id);return {...x,purchaseDate:x.purchaseDate.slice(0,10)};});}
