import type { Item } from './types';
export function today(){return dateString(new Date());}
export function dateString(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function parseDate(value:string){const [y,m,d]=value.slice(0,10).split('-').map(Number);return new Date(y,m-1,d,12);}
export function validDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&dateString(parseDate(value))===value;}
export function heldDays(value:string,at=today()){const utc=(s:string)=>Date.parse(s.slice(0,10)+'T00:00:00Z');return Math.max(1,Math.round((utc(at)-utc(value))/86400000));}
export function unitCost(item:Item,extra=0):number|null{return item.costType==='per_use'?(item.usageCount>0?item.price/item.usageCount:null):item.price/(heldDays(item.purchaseDate)+extra);}
export function summarize(items:Item[]){const active=items.filter(x=>x.status==='using'),daily=active.filter(x=>x.costType==='daily');return {active,daily,value:active.reduce((s,x)=>s+x.price,0),burn:daily.reduce((s,x)=>s+(unitCost(x)||0),0),future:daily.reduce((s,x)=>s+(unitCost(x,30)||0),0)};}
export function validateItem(item:Omit<Item,'id'>){if(!Number.isSafeInteger(item.quantity??1)||(item.quantity??1)<1||(item.quantity??1)>9999)return '数量需为 1 到 9,999 之间的整数';if(!item.name.trim())return '请填写物品名称';if(!Number.isFinite(item.price)||item.price<0||item.price>99999999)return '价格需为 0 到 99,999,999 之间的金额';if(!validDate(item.purchaseDate)||item.purchaseDate>today())return '请选择有效的购入日期，不能晚于今天';if(!Number.isSafeInteger(item.usageCount)||item.usageCount<0)return '使用次数需为非负整数';return '';}
export function readItems(raw:string):Item[]{const value:unknown=JSON.parse(raw);if(!Array.isArray(value))throw Error('数据格式无效');const ids=new Set<string>();return value.map((v:unknown)=>{if(!v||typeof v!=='object')throw Error('物品格式无效');const x=v as Item;if(typeof x.id!=='string'||!x.id||ids.has(x.id)||typeof x.name!=='string'||!Number.isFinite(x.price)||x.price<0||typeof x.purchaseDate!=='string'||!validDate(x.purchaseDate.slice(0,10))||!Number.isInteger(x.usageCount)||x.usageCount<0||!['daily','per_use'].includes(x.costType)||!['using','sold'].includes(x.status)||typeof x.category!=='string'||(x.icon!==undefined&&typeof x.icon!=='string'))throw Error('存在无法读取的物品记录');if(x.quantity!==undefined&&(!Number.isSafeInteger(x.quantity)||x.quantity<1||x.quantity>9999))throw Error('物品数量无效');ids.add(x.id);return {...x,purchaseDate:x.purchaseDate.slice(0,10)};});}

export const SORT_OPTIONS = [['date','购入日期'],['unit','购入单价'],['total','购入总价'],['daily','日均成本'],['per_use','单次成本'],['days','持有时长'],['uses','使用次数'],['name','物品名称']] as const;
export type SortKey = typeof SORT_OPTIONS[number][0];
export function sortValue(x:Item,key:SortKey):number|string|null {switch(key){case 'unit':return x.price/(x.quantity??1);case 'total':return x.price;case 'daily':case 'per_use':return unitCost(x);case 'days':return heldDays(x.purchaseDate);case 'uses':return x.usageCount;case 'name':return x.name;default:return x.purchaseDate;}}
export function sortItems(items:Item[],key:SortKey,ascending:boolean,pinFirst:boolean){return items.filter(x=>key==='daily'?x.costType==='daily':key==='per_use'||key==='uses'?x.costType==='per_use':true).sort((a,b)=>{if(pinFirst&&!!a.isPinned!==!!b.isPinned)return Number(!!b.isPinned)-Number(!!a.isPinned);const av=sortValue(a,key),bv=sortValue(b,key);if(av===null||bv===null)return av===bv?0:av===null?1:-1;const d=typeof av==='string'&&typeof bv==='string'?av.localeCompare(bv,'zh-CN'):Number(av)-Number(bv);return d*(ascending?1:-1)||a.id.localeCompare(b.id);});}
