const assert=require('node:assert/strict');
const ts=require('typescript'),fs=require('node:fs'),vm=require('node:vm');
const js=ts.transpileModule(fs.readFileSync('src/lib/domain.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const moduleObject={exports:{}};vm.runInNewContext(js,{exports:moduleObject.exports,module:moduleObject,require,Date,Set,Error});
const d=moduleObject.exports;
const base={id:'old-1',name:'原有电脑',price:100,purchaseDate:'2024-01-01',usageCount:0,costType:'daily',status:'using',category:'科技',icon:'💻',isPinned:true};
assert.equal(d.heldDays('2024-02-28','2024-03-01'),2);
assert.equal(d.heldDays('2024-03-01','2024-03-01'),1);
assert.equal(d.validDate('2023-02-29'),false);
assert.equal(d.validDate('2024-02-29'),true);
assert.equal(d.unitCost({...base,costType:'per_use'}),null);
assert.equal(d.unitCost({...base,costType:'per_use',usageCount:4}),25);
assert.equal(d.summarize([{...base,costType:'per_use',usageCount:1}]).burn,0);
assert.equal(d.summarize([{...base,status:'sold'}]).value,0);
const old=d.readItems(JSON.stringify([{...base,purchaseDate:'2024-01-01T13:00:00.000Z'}]))[0];
assert.equal(old.id,base.id);assert.equal(old.icon,'💻');assert.equal(old.category,'科技');assert.equal(old.isPinned,true);assert.equal(old.purchaseDate,'2024-01-01');
assert.throws(()=>d.readItems('not json'));assert.throws(()=>d.readItems(JSON.stringify([base,base])));
assert.throws(()=>d.readItems(JSON.stringify([{...base,price:'100'}])));
assert.notEqual(d.validateItem({...base,name:' '}),'');
console.log('PASS: date boundaries, unit separation, sold exclusion, legacy schema, invalid data protection.');
