const assert=require('node:assert/strict');
const ts=require('typescript'),fs=require('node:fs'),vm=require('node:vm');
const js=ts.transpileModule(fs.readFileSync('src/lib/domain.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const moduleObject={exports:{}};vm.runInNewContext(js,{exports:moduleObject.exports,module:moduleObject,require,Date,Set,Error});
const d=moduleObject.exports;
const base={id:'old-1',name:'原有电脑',price:100,purchaseDate:'2024-01-01',usageCount:0,costType:'daily',status:'using',category:'科技',icon:'💻',isPinned:true};
assert.equal(d.heldDays('2024-02-28','2024-03-01'),2);
assert.equal(d.heldDays('2024-03-01','2024-03-01'),1);
assert.equal(d.validDate('2023-02-29'),false);
assert.equal(d.validDate('2024-02-29'),true);
assert.equal(d.unitCost({...base,costType:'per_use'}),null);
assert.equal(d.unitCost({...base,costType:'per_use',usageCount:4}),25);
assert.equal(d.summarize([{...base,costType:'per_use',usageCount:1}]).burn,0);
assert.equal(d.summarize([{...base,status:'sold'}]).value,0);
const old=d.readItems(JSON.stringify([{...base,purchaseDate:'2024-01-01T13:00:00.000Z'}]))[0];
assert.equal(old.id,base.id);assert.equal(old.icon,'💻');assert.equal(old.category,'科技');assert.equal(old.isPinned,true);assert.equal(old.purchaseDate,'2024-01-01');
assert.throws(()=>d.readItems('not json'));assert.throws(()=>d.readItems(JSON.stringify([base,base])));
assert.throws(()=>d.readItems(JSON.stringify([{...base,price:'100'}])));
assert.notEqual(d.validateItem({...base,name:' '}),'');
console.log('PASS: date boundaries, unit separation, sold exclusion, legacy schema, invalid data protection.');
assert.equal(d.sortValue(base,'unit'),100);
assert.equal(d.sortValue({...base,quantity:4},'unit'),25);
assert.equal(d.unitCost({...base,quantity:4,costType:'per_use',usageCount:2}),50);
assert.throws(()=>d.readItems(JSON.stringify([{...base,quantity:0}])));
assert.notEqual(d.validateItem({...base,quantity:1.5}),'');
const sample=[{...base,id:'a',price:100,quantity:1,isPinned:false},{...base,id:'b',price:120,quantity:4,isPinned:true},{...base,id:'c',price:50,isPinned:false,costType:'per_use',usageCount:0}];
assert.equal(d.sortItems(sample,'unit',true,false).map(x=>x.id).join(','),'b,c,a');
assert.equal(d.sortItems(sample,'total',false,false).map(x=>x.id).join(','),'b,a,c');
assert.equal(d.sortItems(sample,'total',true,true)[0].id,'b');
assert.equal(d.sortItems(sample,'daily',true,false).length,2);
assert.equal(d.sortItems(sample,'per_use',false,false).length,1);
assert.equal(d.sortItems([...sample,{...base,id:'d',costType:'per_use',usageCount:2}],'per_use',false,false).map(x=>x.id).join(','),'d,c');
console.log('PASS: quantity compatibility, total-based amortization, ordering, pin priority, incomparable units, missing cost last.');
