'use client';
import {useState} from 'react';
import type {Item} from '@/lib/types';
import {today,heldDays,validateItem} from '@/lib/domain';
import {Modal,Choice,Calendar,PickerRow,Segments,Icon,CATEGORIES,LABELS,allowedIcons,linkedIcon,categoryIcon} from './controls';
export function Editor({item,categories,onSave,onClose}:{item?:Item;categories:string[];onSave:(item:Omit<Item,'id'>)=>boolean;onClose:()=>void}){
 const [form,setForm]=useState<Omit<Item,'id'>>(()=>item?{...item}:{name:'',price:0,purchaseDate:today(),costType:'daily',usageCount:0,status:'using',category:'数码',icon:'laptop'});
 const [picker,setPicker]=useState(''),[error,setError]=useState('');
 const options=Array.from(new Set([...CATEGORIES.map(x=>x[0]),...categories,form.category]));
 function changeCategory(category:string){setForm(f=>({...f,category,icon:linkedIcon(category,f.icon)}));setPicker('')}
 const iconOptions=[...allowedIcons(form.category)];if(form.icon&&!iconOptions.includes(form.icon))iconOptions.push(form.icon);
 const cost=form.costType==='daily'?form.price/heldDays(form.purchaseDate):form.usageCount?form.price/form.usageCount:null;
 return <Modal title={item?'编辑物品':'添加物品'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const failure=validateItem(form);if(failure){setError(failure);return}if(onSave({...form,name:form.name.trim()}))onClose();else setError('保存失败，修改尚未保存。')}}><p className="muted small">{item?'修改记录，成本会自动重新计算。':'记下它，让每一次使用都有迹可循。'}</p><div className="form-section"><h3>这是什么好物</h3><div className="surface"><div className="form-row form-name"><Icon name={form.icon}/><input aria-label="物品名称" placeholder="例如：我的新耳机" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength={60} required/></div><PickerRow label="分类" value={form.category} icon={categoryIcon(form.category)} onClick={()=>setPicker('category')}/><PickerRow label="图标" value={LABELS.find(x=>x[0]===form.icon)?.[1]||'原有图标'} icon={form.icon} onClick={()=>setPicker('icon')}/></div></div><div className="form-section"><h3>购入信息</h3><div className="surface"><div className="form-row"><label htmlFor="price">购入价格</label><span className="muted">¥</span><input id="price" type="number" inputMode="decimal" min={0} max={99999999} step=".01" value={form.price} placeholder="0.00" onChange={e=>setForm({...form,price:Number(e.target.value)})} required/></div><PickerRow label="购入日期" value={form.purchaseDate.replaceAll('-',' / ')} icon="calendar-days" onClick={()=>setPicker('date')}/></div></div><div className="form-section"><h3>怎样计算成本</h3><Segments options={[["daily","按天均摊"],["per_use","按次使用"]]} value={form.costType} onChange={v=>setForm({...form,costType:v as Item['costType']})}/>{form.costType==='per_use'&&<div className="surface" style={{marginTop:10}}><div className="form-row"><label htmlFor="uses">累计使用次数</label><input id="uses" type="number" min={0} max={99999999} step={1} inputMode="numeric" value={form.usageCount} onChange={e=>setForm({...form,usageCount:Number(e.target.value)})}/></div></div>}<p className="live-cost">{cost===null?'记录第一次使用后开始计算':<>当前{form.costType==='daily'?'日均':'每次'}约 <b>¥{cost.toFixed(2)}</b></>}</p></div><div className="surface"><PickerRow label="物品状态" value={form.status==='using'?'使用中':'已售出'} onClick={()=>setPicker('status')}/></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="dialog-footer"><button type="submit" className="primary-button full">{item?'保存修改':'添加物品'}</button><p className="footnote" style={{textAlign:'center'}}>数据保存在当前设备</p></div></form>
 {picker==='category'&&<Choice title="选择分类" category description="选择分类后，自动匹配相关图标。" options={options.map(x=>({value:x,label:x,icon:categoryIcon(x)}))} value={form.category} onSelect={changeCategory} onCreate={changeCategory} onClose={()=>setPicker('')}/>}
 {picker==='icon'&&<Choice title="选择图标" description={`${form.category} · ${iconOptions.length} 个可用图标`} options={iconOptions.map(x=>({value:x,label:LABELS.find(y=>y[0]===x)?.[1]||'原有图标',icon:x}))} value={form.icon||'box'} onSelect={v=>{setForm({...form,icon:v});setPicker('')}} onClose={()=>setPicker('')}/>}
 {picker==='status'&&<Choice title="物品状态" category options={[{value:'using',label:'使用中',icon:'box'},{value:'sold',label:'已售出',icon:'check'}]} value={form.status} onSelect={v=>{setForm({...form,status:v as Item['status']});setPicker('')}} onClose={()=>setPicker('')}/>}
 {picker==='date'&&<Calendar value={form.purchaseDate} onClose={()=>setPicker('')} onSelect={v=>{setForm({...form,purchaseDate:v});setPicker('')}}/>}
 </Modal>
}

